name-template: 'Release ${{version}}'
tag-template: 'v${{version}}'
template: |
  ## Release Notes for ${{version}}
  
  **Release Date:** ${{date}}
  
  ### 🛠 Breaking Changes
  ${{changes-breaking}}
  
  ### 🎉 New Features
  ${{changes-features}}
  
  ### 🐛 Fixes
  ${{changes-fixes}}
  
  ### 🔄 Improvements
  ${{changes-improvements}}
  
  ### 📜 Other Changes
  ${{changes-other}}
  
  ### 🙏 Thanks to Contributors
  ${{contributor-list}}

categories:
  - title: Breaking Changes 🛠
    labels:
      - breaking-change
  - title: Fixes 🐛
    labels:
      - bug
      - fix
      - defect
  - title: Exciting New Features 🎉
    labels:
      - feature
  - title: Other Changes
    labels:
      - "*"
